spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/diplom2
    username: root
    password: SHreder9955
  flyway:
    baseline-on-migrate: true
