//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 02:44:34 PM KRAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://newnetshop.com/shopnetnew/ws/users", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.newshop.shopnetnew.ws.Users;
